apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: f1ov671j5-python-gitops
  description: This is GitOps manifest for f1ov671j5-python   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: tssc/gitops=f1ov671j5-python
    backstage.io/kubernetes-id: f1ov671j5-python 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: f1ov671j5-python
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:f1ov671j5-python
